config:
  dl4miceverywhere:
    cuda_version: 11.8.0
    description: Noise2Void_3D_DL4Mic is the conversion of the 3D Noise2Void from ZeroCostDL4Mic.
    dl4miceverywhere_version: 0.0.1
    docker_hub_image: Noise2Void_3D_ZeroCostDL4Mic-z1.16.2-d0.0.1
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/Noise2Void_3D_ZeroCostDL4Mic.ipynb
    notebook_version: 1.16.2
    python_version: 3.1
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/Noise2Void_3D_requirements_simple.txt
    sections_to_remove: 1.1. 1.2. 2. 6.2.
    ubuntu_version: 22.04
