channels:
- conda-forge
- anaconda
- defaults
dependencies:
- constructor
- make
- freetype
- libsm-cos6-x86_64
- curl
- git
- ffmpeg
- pkg-config
- nodejs
- pyinstaller
- pip
- zlib
- cudatoolkit=11.0 # Adjust the version number as needed
- pip:
  - pip
  - nvidia-cudnn-cu11==8.6.0.163 # if GPU_FLAG==1
  - nbformat
  - jupyterlab
  - ipywidgets
