notebook_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/pix2pix_ZeroCostDL4Mic.ipynb
requirements_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/master/requirements_files/pix2pix_requirements_simple.txt
base_img: tensorflow/tensorflow:2.8.0-gpu
sections_to_remove: 2. 6.3.