notebook_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/0d2bcef99cfd76294b9b91243d68ba6c6727c4fe/Colab_notebooks/pix2pix_ZeroCostDL4Mic.ipynb?raw=true
requirements_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/cfbb6b9d7a5b2d190749e708c39b5c3b98b0f70d/requirements_files/pix2pix_requirements_simple.txt?raw=true
cuda_version: 11.8.0
ubuntu_version: 22.04
python_version: 3.8
sections_to_remove: 2. 6.3. 
version: 0.0.1
description: "pix2pix_DL4Mic is the conversion of the pix2pix from ZeroCostDL4Mic."