#!/bin/bash

# Shared DL4MicEverywhere launcher status contract.
#
# 0         Normal completion.
# 42        Windows uninstall handoff (existing contract).
# 90-94     Controlled outcomes: intentional stops that are not failures.
# 95-103    Handled stops: known problems with a tailored user-facing message.
# Other     Unexpected/unclassified failure.

DL4ME_STATUS_UNINSTALL_HANDOFF=42
DL4ME_STATUS_RESTART_LATER=90
DL4ME_STATUS_RESTART_SCHEDULED=91
DL4ME_STATUS_GUI_CLOSED=92
DL4ME_STATUS_UPDATE_COMPLETE=93
DL4ME_STATUS_USER_CANCELLED=94

DL4ME_STATUS_HISTORICAL_IMAGE_UNAVAILABLE=95
DL4ME_STATUS_INPUT_INVALID=96
DL4ME_STATUS_DEPENDENCY_FAILED=97
DL4ME_STATUS_DOCKER_IMAGE_FAILED=98
DL4ME_STATUS_POST_BUILD_FAILED=99
DL4ME_STATUS_CONTAINER_RUNTIME_FAILED=100
DL4ME_STATUS_UPDATE_FAILED=101
DL4ME_STATUS_UNINSTALL_FAILED=102
DL4ME_STATUS_PREREQUISITE_FAILED=103
