config:
  dl4miceverywhere:
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/fnet_2D_ZeroCostDL4Mic.ipynb
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/fnet_2D_requirements_simple.txt
    cuda_version: 11.8.0
    ubuntu_version: 22.04
    python_version: 3.7
    sections_to_remove: 1.1. 1.2. 2. 6.3.
    notebook_version: 1.14.1
    description: "fnet_2D_DL4Mic is the conversion of the 2D fnet from ZeroCostDL4Mic."