config:
  dl4miceverywhere:
    cuda_version: 11.8.0
    description: fnet_2D_DL4Mic is the conversion of the 2D fnet from ZeroCostDL4Mic.
    dl4miceverywhere_version: 0.0.1
    docker_hub_image: fnet_2D_ZeroCostDL4Mic-z1.14.1-d0.0.1
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/fnet_2D_ZeroCostDL4Mic.ipynb
    notebook_version: 1.14.1
    python_version: 3.7
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/fnet_2D_requirements_simple.txt
    sections_to_remove: 1.1. 1.2. 2. 6.3.
    ubuntu_version: 22.04
