notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/CARE_3D_ZeroCostDL4Mic.ipynb
requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/CARE_3D_requirements_simple.txt
cuda_version: 11.8.0
ubuntu_version: 22.04
python_version: 3.10
sections_to_remove: 1.1. 1.2. 2. 6.2. 
version: 0.1.0
description: "CARE_3D_DL4Mic is the conversion of the 3D CARE from ZeroCostDL4Mic."