config:
  dl4miceverywhere:
    cuda_version: 11.8.0
    description: CARE_3D_DL4Mic is the conversion of the 3D CARE from ZeroCostDL4Mic.
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/CARE_3D_ZeroCostDL4Mic.ipynb
    notebook_version: 1.15.2
    python_version: '3.10'
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/CARE_3D_requirements_simple.txt
    sections_to_remove: 1.1. 1.2. 2. 6.2.
    ubuntu_version: '22.04'
