config:
  dl4miceverywhere:
    notebook_url: https://github.com/bioimage-io/spec-bioimage-io/blob/65c416542c4afc2865335ab5022a24220272b217/example_use/load_model_and_create_your_own.ipynb
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/3D_RCAN_requirements_simple.txt
    cuda_version: 11.2
    ubuntu_version: '22.04'
    python_version: '3.10'
    sections_to_remove:
    description: BMZ load model and create your own
    notebook_version: 1.0.0
    dl4miceverywhere_version: 1.0.0
