notebook_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/388b177f77f12f4eef49b5740ccd3b00e074a03d/Colab_notebooks/CycleGAN_ZeroCostDL4Mic.ipynb?raw=true
requirements_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/388b177f77f12f4eef49b5740ccd3b00e074a03d/requirements_files/CycleGAN_requirements_simple.txt?raw=true
cuda_version: 11.8.0
ubuntu_version: 22.04
python_version: 3.10
sections_to_remove: 2. 6.3. 
version: 0.0.1
description: "CycleGAN_DL4Mic is the conversion of the CycleGAN from ZeroCostDL4Mic."