notebook_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/0d2bcef99cfd76294b9b91243d68ba6c6727c4fe/Colab_notebooks/fnet_2D_ZeroCostDL4Mic.ipynb?raw=true
requirements_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/302e4fe2bdf0a5df01aa2b3fc8fdf0de958155b7/requirements_files/fnet_2D_requirements_simple.txt?raw=true
cuda_version: 11.8.0
ubuntu_version: 22.04
python_version: 3.7
sections_to_remove: 1.1. 1.2. 2. 6.3.
version: 0.0.1
description: "fnet_2D_DL4Mic is the conversion of the 2D fnet from ZeroCostDL4Mic. "