notebook_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/YOLOv2_ZeroCostDL4Mic.ipynb
requirements_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/master/requirements_files/YOLO_v2_requirements_simple.txt
base_img: tensorflow/tensorflow:2.8.0-gpu
sections_to_remove: 1.1. 1.2. 2. 6.3.