notebook_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/0d2bcef99cfd76294b9b91243d68ba6c6727c4fe/Colab_notebooks/Deep-STORM_2D_ZeroCostDL4Mic.ipynb?raw=true
requirements_url: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/0d2bcef99cfd76294b9b91243d68ba6c6727c4fe/requirements_files/DeepSTORM_requirements_simple.txt?raw=true
cuda_version: 11.8.0
ubuntu_version: 22.04
python_version: 3.10
sections_to_remove: 2. 6.4.  
version: 0.0.1
description: "Deep-STORM_2D_DL4Mic is the conversion of the 2D Deep-STORM from ZeroCostDL4Mic.  "