name: Build Docker Images

on:
    workflow_dispatch:
        inputs:
          logLevel:
            description: "Log level"
            required: true
            default: "warning"
            type: choice
            options:
              - info
              - warning
              - debug

jobs:
    setup_environment:
        name: Setup environment
        runs-on: [self-hosted, ocbmacmini]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

    list_configs:
        name: Get the list of configuration files on the repository
        runs-on: [self-hosted, ocbmacmini]
        needs: setup_environment
        outputs: 
            configurations: ${{ steps.list_configs.outputs.configurations }}
        steps:
            - name: List configurations
              id: list_configs
              run: |
                configurations=$(ls ./notebooks/*/*/configuration.yaml)
                echo $configurations
                echo "configurations=$configurations" >> $GITHUB_OUTPUT

    build_images:
        name: Build Docker images
        runs-on: [self-hosted, ocbmacmini]
        needs: [setup_environment, list_configs]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
