name: Build Docker Images

on:
    workflow_dispatch:
        inputs:
          logLevel:
            description: "Log level"
            required: true
            default: "warning"
            type: choice
            options:
              - info
              - warning
              - debug

jobs:
    setup_environment:
        name: Setup environment
        runs-on: [self-hosted, dl4miceverywhere-builder]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Setup Python
              uses: actions/setup-python@v4.7.1
              with:
                  python-version: 3.10

    list_configs:
        name: Get the list of configuration files on the repository
        runs-on: [self-hosted, ocbmacmini]
        needs: setup_environment
        outputs: 
            matrix: ${{ steps.list_configs.outputs.configurations }}
        steps:
            - name: List configurations
              id: list_configs
              run: |
                configurations_list=$(ls ./notebooks/*/*/configuration.yaml)
                echo "Start"
                files_json="{\"include\":[{\"notebook\":\""
                echo "$files_json"
                first=true
                for file in $configurations_list; do
                  echo "$file was changed"
                  if [ "$first" = true ]; then
                    files_json+=$file
                    first=false
                  else
                    files_json+="\"},{\"notebook\":\""$file
                  fi
                  echo "$files_json"
                done
                files_json+="\"}]}"
                echo "$files_json"
                echo "matrix=$files_json" >> $GITHUB_OUTPUT
                echo "END"

    build_images:
        name: Build Docker images
        runs-on: [self-hosted, ocbmacmini]
        needs: [setup_environment, list_configs]
        strategy:
          # super important if you want to see all results, even if one fails
          # fail-fast is true by default
          fail-fast: false
          matrix: ${{ fromJson(needs.list_configs.outputs.matrix) }} 
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
