name: Build and push Docker Images

on:
  release:
    types: [published]
  workflow_dispatch:
                  
env:
  REGISTRY_IMAGE: henriqueslab/dl4miceverywhere

jobs:
  list_configs:
    name: Get the list of configuration files on the repository
    runs-on: [self-hosted, dl4miceverywhere-builder]
    outputs: 
      matrix: ${{ steps.config_list.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List configurations
        id: config_list
        run: |
          configurations_list=$(ls ./notebooks/*/*/configuration.yaml)
          echo "Start"
          files_json="{\"include\":[{\"notebook\":\""
          echo "$files_json"
          first=true
          for file in $configurations_list; do
            echo "$file was changed"
            if [ "$first" = true ]; then
              files_json+=$file
              first=false
            else
              files_json+="\"},{\"notebook\":\""$file
            fi
            echo "$files_json"
          done
          files_json+="\"}]}"
          echo "$files_json"
          echo "matrix=$files_json" >> $GITHUB_OUTPUT
          echo "END"
      - name: Print matrix
        run: |
          echo ${{ steps.config_list.outputs.matrix }}

  version-matrix:
    name: Call the building and pushing
    needs: list_configs
    strategy:
      # super important if you want to see all results, even if one fails
      # fail-fast is true by default
      fail-fast: false
      matrix: ${{ fromJson(needs.list_configs.outputs.matrix) }} 
    uses: ./.github/workflows/build_docker_images_aux.yml # calls the one above ^
    with:
      config_file: ${{ matrix.notebook }}
    secrets: inherit
