name: update-documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install requirements
        run: pip install -r .tools/requirements.txt
      - name: generate notebooks list
        run: python3 .tools/list_of_notebooks.py
      - name: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: boot - update notebook list