name: Check modified configuration.yaml

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
    branches:
      - main
jobs:
  extract_changed_files:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]

    name: Find changed-files
    outputs:
      matrix: ${{ steps.create-json.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed configuration.yaml on the commint
        id: changed-files
        uses: tj-actions/changed-files@v38
        with:
         files: '**/configuration.yaml'
      - if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        name: List and extract all changed files
        id: create-json
        run: |
          echo "Start"
          files_json="{\"include\":[{\"notebook\":\""
          echo "$files_json"
          first=true
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            if [ "$first" = true ]; then
              files_json+=$file
              first=false
            else
              files_json+="\"},{\"notebook\":\""$file
            fi
            echo "$files_json"
          done
          files_json+="\"}]}"
          echo "$files_json"
          echo "matrix=$files_json" >> $GITHUB_OUTPUT
          echo "END"
    
  version-matrix:
    if: ${{ needs.extract_changed_files.outputs.matrix != '' }}
    name: Check modified configuration.yaml
    needs: extract_changed_files
    strategy:
      # super important if you want to see all results, even if one fails
      # fail-fast is true by default
      fail-fast: false
      matrix: ${{ fromJson(needs.extract_changed_files.outputs.matrix) }} 
    uses: ./.github/workflows/check_configuration.yml # calls the one above ^
    with:
      config_file: ${{ matrix.notebook }}
    secrets: inherit
