# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  release:
    types: [published]

  workflow_dispatch:
      inputs:
        logLevel:
          description: "Log level"
          required: true
          default: "warning"
          type: choice
          options:
            - info
            - warning
            - debug

jobs:
  list_configs:
    name: Get the list of configuration files on the repository
    runs-on: [self-hosted, dl4miceverywhere-builder]
    outputs: 
        configurations: ${{ steps.list_configs.outputs.configurations }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: List configurations
        id: list_configs
        run: |
            configurations_list=$(ls ./notebooks/*/*/configuration.yaml)
            echo "Start"
            files_json="{\"include\":[{\"notebook\":\""
            echo "$files_json"
            first=true
            for file in  $configurations_list; do
              echo "$file was changed"
              if [ "$first" = true ]; then
                files_json+=$file
                first=false
              else
                files_json+="\"},{\"notebook\":\""$file
              fi
              echo "$files_json"
            done
            files_json+="\"}]}"
            echo "$files_json"
            echo "configurations=$files_json" >> $GITHUB_OUTPUT
            echo "END"

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, dl4miceverywhere-builder]
    needs: list_configs
    strategy:
        matrix: 
            gpu: [0, 1]
            config_file: ${{ fromJson(needs.list_configs.outputs.configurations) }} 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get version
        uses: mikefarah/yq@master
        id: version
        with:
            cmd: yq '.version' '${{ matrix.config_file }}'  
    
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push image
        run: |
            aux_docker_tag="$(basename $notebook_path .ipynb)"
            notebook_name="$(echo $docker_tag | tr '[:upper:]' '[:lower:]')"
            if [ ${{ matrix.gpu }} -eq 0 ]; then
                tag=henriqueslab/dl4miceverywhere:"$notebook_name"-${{ steps.version.outputs.result }}
                bash launch.sh -c '${{ matrix.config_file }}' -d . -o . -x -t "$tag"
            else
                tag=henriqueslab/dl4miceverywhere:"$notebook_name"-${{ steps.version.outputs.result }}-gpu
                bash launch.sh -c '${{ matrix.config_file }}' -d . -o . -x -g -t "$tag"
            fi
            docker image push "$tag"
