name: Build Installer
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          # condarc-file: etc/example-condarc.yml
          # auto-activate-base: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          mamba-version: "*"
          use-mamba: true
      - name: Build Installer
        run: constructor .
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: installer-${{ matrix.python-version }}
          path: Install_*.sh
