name: Build Installer
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          use-mamba: true
      - name: constructor build
        run: constructor
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: installer-${{ matrix.python-version }}
          path: Install_*.sh
