name: Build Installer
on:
  push:
    branches:
      - main
jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
       os: [ubuntu]
      #  os: [ubuntu, windows, macos]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        include:
          - os: ubuntu
            shell: bash -l {0}
          # - os: windows
          #   shell: cmd /C call {0}
          # - os: macos
          #   shell: bash -l {0}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          use-mamba: true
      - name: constructor 
        run: constructor --output-dir dist/main 
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: installer-${{ matrix.python-version }}-${{ matrix.os }}
          path: dist/main/**/*
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     files: dist/main/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      # - name: Create Draft Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     files: ./**/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/main/*"  # Replace with your actual artifacts path
          # bodyFile: "path/to/release-notes.md"   # Replace with your actual release notes file
                
        