name: Update versioning on the configuration files
on:
  release:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install requirements
        run: pip install -r .tools/requirements.txt
      - name: update all the configurations
        run: python3 .tools/update_configuration.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: boot - update configuration version tag
