name: Update repository version and docker tag on configuration files
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update_configuration:
    name: Update repository version and docker tag on configuration
    runs-on: [self-hosted, dl4miceverywhere-builder]
    steps:
      - name: Clone DL4MicEverywhere repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: Install requirements
        run: pip install -r .tools/requirements.txt
      - name: Update all the configurations
        run: python3 .tools/python_tools/update_configuration.py
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: GitHub Action - Update repository version and docker tag on configuration
